# Deploy finance-backend
trigger:
  branches:
    include: [main]

variables:
  - group: devgiglio-env
  - group: devgiglio-secrets
  - name: APP_NAME
    value: finance-backend
  - name: STACK
    value: python
  - name: DEPLOY_ENABLED
    value: "true"
  - name: TEST_ENABLED
    value: "false"
  - name: DOCS_ENABLED
    value: "false"

resources:
  repositories:
    - repository: templates
      type: github
      name: gipierogiglio-prog/devgiglio-pipelines
      ref: main
      endpoint: gipierogiglio-prog

pool: Default

stages:
  - template: stages/build/python-build.yml@templates
    parameters:
      appName: 

  - ${{ if eq(variables.TEST_ENABLED, "true") }}:
    - template: stages/test/python-test.yml@templates
      parameters:
        appName: 

  - ${{ if eq(variables.DOCS_ENABLED, "true") }}:
    - template: stages/docs/technical-doc.yml@templates
      parameters:
        appName: 

  - ${{ if eq(variables.DEPLOY_ENABLED, "true") }}:
    - template: stages/deploy/deploy-vps.yml@templates
      parameters:
        appName: 
